### ISSUE TITLE
L6 data from Ublox

### ISSUE THREAD

**Issue by susilosarimun** [yoronneko/qzsl6tool#1]
Dear Yoronneko,

Is this library support for L6 correction data from ublox D9C raw data correction?

Thank you very much

Susilo

**Comment by yoronneko** [comment]
Dear Susilo,

No, the current codes cannot decode u-blox NEO-D9C raw data (UBX-RXM-QZSSL6).

With D9C standalone mode (described on page 7 in C101-D9C Application board user guide), we may obtain QZSS raw messages.

https://content.u-blox.com/sites/default/files/C101-D9C-AppBoard_UserGuide_UBX-21009111.pdf

Thank you very much for your question.

Satoshi
